import type { NetCopy } from './types';

export const BUILTIN_NETCOPY: NetCopy[] = [
  // ── 悬念钩子 · 中文 ──
  {
    id: 'hook-bihua',
    text: '别划走！这条可能是你今年看到最有用的东西。',
    source: '抖音/小红书开场白公式',
    category: '悬念钩子',
    analysis: '「别划走」直接对抗平台机制，承认用户有划走的权利反而制造停顿。「可能」降低承诺成本，「今年」制造时间紧迫感。三招合一，换来前三秒。',
    lang: 'zh',
  },
  {
    id: 'hook-90percent',
    text: '90%的人第一步就做错了，难怪没有效果。',
    source: '内容创作钩子公式',
    category: '悬念钩子',
    analysis: '触发认知失调——「我是那90%吗？」不确定感比确定感更难忽视。「难怪没效果」给过去的失败找到了归因，让人如释重负又想立刻点开验证。',
    lang: 'zh',
  },
  {
    id: 'hook-wule',
    text: '我悟了：以前做错了这件事，现在全说给你听。',
    source: '「顿悟体」，小红书高频句式',
    category: '悬念钩子',
    analysis: '「顿悟」是高权威信号——博主把自己置于「已经走过弯路」的位置，信息不对称天然存在。读者感受到的是「免费省了试错成本」，而非「被推销」。',
    lang: 'zh',
  },
  {
    id: 'hook-fangshou',
    text: '我反手就给你看看，什么叫做真正的××。',
    source: '抖音口播高频句式',
    category: '悬念钩子',
    analysis: '「反手」是网络动词，意味着轻松自如、无需努力，暗示对方是行家。这句话先建立权威感，再用悬念拉住注意力，适合任何技能展示类内容。',
    lang: 'zh',
  },
  {
    id: 'hook-meirenjiangni',
    text: '没人告诉你的是——',
    source: '小红书/B站信息差钩子',
    category: '悬念钩子',
    analysis: '「没人」制造信息特权感，破折号制造悬念停顿。六个字就完成了：建立稀缺性 → 激发好奇 → 让用户觉得接下来的内容是独家情报。',
    lang: 'zh',
  },

  // ── 情绪共鸣 · 中文 ──
  {
    id: 'emotion-banwei',
    text: '刚下班，还没洗掉班味儿。',
    source: '打工人网络用语，2024年流行',
    category: '情绪共鸣',
    analysis: '「班味儿」是2024年的年度词汇，把上班的疲惫和异化感具象化成一种「气味」。这句话让人秒懂、秒共鸣，评论区必然是「一模一样」。',
    lang: 'zh',
  },
  {
    id: 'emotion-yun',
    text: '允许一切发生。',
    source: '「松弛感」文化，2023-2024年小红书关键词',
    category: '情绪共鸣',
    analysis: '四个字的解药，针对的是「控制焦虑」——现代人的集体病。它不给方案，只给一个态度，反而让人停下来思考。松弛感文案的核心是「反力气」。',
    lang: 'zh',
  },
  {
    id: 'emotion-chengren-bengkui',
    text: '成年人的崩溃，往往是静悄悄的。',
    source: '网络流行语，近年高频转发',
    category: '情绪共鸣',
    analysis: '「往往」留有余地，让每个人都能对号入座。「静悄悄」戳中了独自压抑、不被看见的具体感受，而非泛泛的「压力大」。被看见感是转发的驱动力。',
    lang: 'zh',
  },
  {
    id: 'emotion-daxuesheng-kuole',
    text: '大学生的快乐很简单：今天没课。',
    source: '大学生网络用语',
    category: '情绪共鸣',
    analysis: '「快乐很简单」是预期管理——拉低预期之后，「没课」这个小事就足以成为节日。反差制造幽默，幽默制造转发。这个句式可以套任何人群。',
    lang: 'zh',
  },
  {
    id: 'emotion-rensheng-kuangye',
    text: '人生是旷野，不是轨道。',
    source: '网络流行语，2023年爆发',
    category: '情绪共鸣',
    analysis: '给「偏离主流路径」的人一个体面的自我叙述框架。不是「我失败了」，而是「我在探索」。两个意象的对立即是全部论述，无需解释。',
    lang: 'zh',
  },

  // ── 反差对比 · 中文 ──
  {
    id: 'contrast-bumaiguixing',
    text: '不是贵替买不起，而是平替更有性价比。',
    source: '小红书消费句式，2023-2024年高频',
    category: '反差对比',
    analysis: '把「买不起」的尴尬转化成「我更聪明」的优越感。这个句式重新框架了消费行为，让降级消费变成主动选择，是情绪价值的绝妙包装。',
    lang: 'zh',
  },
  {
    id: 'contrast-citybucity',
    text: 'City不City啊？',
    source: '2024年中文互联网流行梗，外国博主走红后扩散',
    category: '反差对比',
    analysis: '把英文单词和中文句式混搭，本身就是一种错位幽默。「不City」成为描述「土气/过时」的高频用法——用洋气的词说土气的事，反差即笑点。',
    lang: 'zh',
  },
  {
    id: 'contrast-lanjuan',
    text: '不卷了，躺平了，但又没完全躺平。',
    source: '打工人自我调侃，网络流行',
    category: '反差对比',
    analysis: '「没完全躺平」是关键——彻底躺平太激进，完全内卷太累，这句话精准描述了大多数人的灰色地带状态，让人忍不住转发「就是我」。',
    lang: 'zh',
  },
  {
    id: 'contrast-dongyu-apple',
    text: '这颗苹果，经历了一百八十天的日照，大地的滋养，和一个农民一生的等待。',
    source: '东方甄选/董宇辉风格文案',
    category: '反差对比',
    analysis: '把卖苹果变成讲故事。「一百八十天」具体，「一生的等待」宏大，两个时间尺度并置制造震撼感。这种诗意化的商品描述颠覆了直播带货的话语体系。',
    lang: 'zh',
  },

  // ── 极简有力 · 中文 ──
  {
    id: 'punch-zhide',
    text: '你值得被好好对待。',
    source: '情绪价值品牌文案，现在普遍使用',
    category: '极简有力',
    analysis: '「值得」是关键词——它把消费从外部需求（我想要）变成内部授权（我配得上）。简单到像废话，却戳中了现代人普遍的配得感缺失。',
    lang: 'zh',
  },
  {
    id: 'punch-zilu',
    text: '自律给我自由。',
    source: 'Keep',
    category: '极简有力',
    analysis: '矛盾即张力——「自律」和「自由」是反义词，并排产生停顿，让人忍不住在脑海里验证这个逻辑，验证完就信了。四字包含了完整的哲学命题。',
    lang: 'zh',
  },
  {
    id: 'punch-athlete',
    text: '你好，运动员。',
    source: 'Keep App 打招呼语',
    category: '极简有力',
    analysis: '称谓赋能：用户登录的瞬间被授予「运动员」身份，而非「用户」。身份先行，行为跟上——你不是来健身的普通人，你是运动员。',
    lang: 'zh',
  },
  {
    id: 'punch-mingtian-jian',
    text: '明天见。',
    source: 'Manner Coffee 咖啡杯口号',
    category: '极简有力',
    analysis: '三个字完成了所有品牌想说的：我们明天还会在，你也会回来，这是一段关系不是一次交易。比任何「欢迎再次光临」都有温度。',
    lang: 'zh',
  },

  // ── 身份认同 · 中文 ──
  {
    id: 'identity-dapai',
    text: '找搭子，不孤单。',
    source: '「搭子文化」，2023-2024年流行',
    category: '身份认同',
    analysis: '「搭子」文化折射出年轻人既渴望陪伴又害怕深度关系的矛盾。这句话召唤了一个新的社会角色认同——你不是内向，你只是还没找到搭子。',
    lang: 'zh',
  },
  {
    id: 'identity-xianyu',
    text: '打工人，打工魂，打工都是人上人。',
    source: '打工人网络梗，2020年兴起并延续',
    category: '身份认同',
    analysis: '借用励志语法，填入自嘲内容。「人上人」的目标被替换成「打工人」的现实，荒诞中带出一种苦中作乐的共同体感——我们都是这样，所以我们是一类人。',
    lang: 'zh',
  },

  // ── 悬念钩子 · 英文 ──
  {
    id: 'hook-pov',
    text: 'POV: you finally stopped caring what people think.',
    source: 'TikTok/Reels 代入感句式，2022-2025年高频',
    category: '悬念钩子',
    analysis: '"POV:" puts the viewer inside a fantasy they already want. You\'re not watching someone else\'s story — you\'re living yours. The hook works because the scenario IS the aspiration.',
    lang: 'en',
  },
  {
    id: 'hook-sign',
    text: 'This is your sign to quit the job / book the trip / send the text.',
    source: 'TikTok/Instagram caption formula, widely used since 2021',
    category: '悬念钩子',
    analysis: 'Grants permission the reader was already looking for. It reframes the algorithm as fate — you didn\'t scroll to this, you were *meant* to see it. Urgency without pressure.',
    lang: 'en',
  },
  {
    id: 'hook-nobody-talking',
    text: "No one is talking about the fact that...",
    source: 'TikTok contrarian hook, peak usage 2022-2025',
    category: '悬念钩子',
    analysis: 'Manufactures information scarcity. If no one else is saying it, and you\'re about to, you\'re either brave or exclusive — either way, the viewer is compelled to hear what the crowd missed.',
    lang: 'en',
  },
  {
    id: 'hook-tried30days',
    text: 'I tried [X] for 30 days. Here\'s what actually happened.',
    source: 'YouTube/TikTok experiment format, 2020s dominant structure',
    category: '悬념钩子',
    analysis: '"Actually" is the key word — it promises to cut through the hype and give you the real version. The format combines credibility (I did the work), sacrifice (30 days!), and truth-telling. Three appeals in one structure.',
    lang: 'en',
  },

  // ── 反差对比 · 英文 ──
  {
    id: 'contrast-liquid-death',
    text: 'Murder your thirst.',
    source: 'Liquid Death, canned water brand, 2019-present',
    category: '反差对比',
    analysis: 'Death-metal branding for... water. The extreme violence of the language against the mundanity of the product IS the entire joke and selling point. Standing out in a commoditized category by being maximally unlike everything else.',
    lang: 'en',
  },
  {
    id: 'contrast-deinfluencing',
    text: "Don't buy it. Seriously. You don't need it.",
    source: 'De-influencing trend, TikTok 2023',
    category: '反差对比',
    analysis: 'Anti-recommendation as recommendation. Telling people NOT to buy something builds more trust than any ad — and paradoxically drives more interest. The 2023 "de-influencing" movement made this the most effective brand-adjacent content format.',
    lang: 'en',
  },
  {
    id: 'contrast-understood',
    text: 'Understood the assignment.',
    source: 'Gen Z internet slang, mainstream 2021-2025',
    category: '反差对比',
    analysis: 'Corporate speak ("assignment") meets casual approval. The phrasing implies a standard was set and met — it\'s both a compliment and a flex. Brands use it to signal cultural fluency; the irony is that overusing it kills that fluency immediately.',
    lang: 'en',
  },

  // ── 情绪共鸣 · 英文 ──
  {
    id: 'emotion-rest',
    text: 'Rest is not a reward. It\'s a requirement.',
    source: 'Wellness / anti-hustle content, widely circulated 2022-2025',
    category: '情绪共鸣',
    analysis: 'Reframes a belief the reader already half-holds but feels guilty about. The parallel structure (reward / requirement) makes it quotable. It doesn\'t teach you anything new — it gives you permission to believe what you already wanted to.',
    lang: 'en',
  },
  {
    id: 'emotion-its-giving',
    text: "It's giving main character energy.",
    source: 'Gen Z slang, TikTok origin, mainstream by 2023',
    category: '身份认同',
    analysis: '"Main character" is an identity aspiration — not a description. Calling something/someone "main character energy" elevates it from real life into narrative. The person being described feels seen; the person describing feels like they have cultural taste.',
    lang: 'en',
  },
  {
    id: 'emotion-hot-take',
    text: 'Hot take: [conventional wisdom] is actually wrong.',
    source: 'Twitter/X, newsletter hooks, podcast openers — omnipresent 2020-2025',
    category: '悬念钩子',
    analysis: '"Hot take" signals you\'re about to say something people might disagree with — which is exactly why people keep reading. It transforms opinion into event. The disclaimer does the marketing.',
    lang: 'en',
  },
];
