import type { NetCopy } from './types';

export const BUILTIN_NETCOPY: NetCopy[] = [
  // ── 悬念钩子 · 中文 ──
  {
    id: 'caotaibandui',
    text: '我发现一个秘密：所有看起来很专业的组织，其实都是草台班子。',
    source: '「草台班子」，2023-2024年顶流认知梗',
    category: '悬念钩子',
    analysis: '戳破权威神话。说出这句话的人会被大量转发，因为它把「我也不知道自己在干什么」从个人焦虑变成了集体秘密。认知颠覆 + 解压，双倍传播力。',
    lang: 'zh',
  },
  {
    id: 'yaoli-geidao',
    text: '压力给到你了。',
    source: '体育解说转网络梗，2023-2024年高频用法',
    category: '悬念钩子',
    analysis: '原是体育解说词，被网络剥离语境、用在任何需要「把锅甩出去」的场合。它的好用在于：说完这句话，主动权就转移了，但说话人完全不需要负责任。',
    lang: 'zh',
  },
  {
    id: 'zhudayi-buzaihu',
    text: '主打一个不在乎。',
    source: '「主打一个XX」句式，2023年起爆发',
    category: '悬念钩子',
    analysis: '「主打」是策略词，「不在乎」是结果词，两者结合把消极状态变成了主动选择。这个句式的神奇之处：套什么都成立，套什么都显得有点酷。',
    lang: 'zh',
  },
  {
    id: 'meirenjiangwo',
    text: '没人告诉我原来可以这样。',
    source: '小红书/抖音种草高频起手式',
    category: '悬念钩子',
    analysis: '制造「信息被剥夺」的委屈感，再用「原来」翻转——现在你知道了。读者从受害者秒变受益者。这个情绪弧线是种草视频播放完成率的关键。',
    lang: 'zh',
  },

  // ── 情绪共鸣 · 中文 ──
  {
    id: 'chengniancongwuguoyi',
    text: '成年人崩溃的前一秒，还在问别人「还有什么需要帮忙的吗」。',
    source: '网络流行语，近年高转发',
    category: '情绪共鸣',
    analysis: '具体的细节比宏大的描述更打人。「还有什么需要帮忙的吗」是一个极其精准的场景——很多人读到这里会停住，因为那就是自己。',
    lang: 'zh',
  },
  {
    id: 'bingbu-luo',
    text: '并不是每件事都需要一个结果，有时候就是绷不住了。',
    source: '「绷不住」，2024年流行表达',
    category: '情绪共鸣',
    analysis: '「绷不住」（hold不住了）是当下情绪词，「并不需要结果」给了情绪一个出口而非解决方案。不给答案的文案往往比给答案的更能引起共鸣。',
    lang: 'zh',
  },
  {
    id: 'iperson-chumen',
    text: 'i人出门困难户，今天成功下楼取了外卖。',
    source: 'MBTI梗 × 日常自嘲，2023-2025年小红书主流',
    category: '情绪共鸣',
    analysis: '「i人」（内向型）成为身份标签后，「困难户」把日常小事升格为胜利。自嘲 + 小确幸，评论区会出现大量「同款」。身份认同是这类内容的核心引擎。',
    lang: 'zh',
  },
  {
    id: 'fanfazanle',
    text: '发疯了，谢谢关心，一切都好。',
    source: '发疯文学，2023年后持续流行',
    category: '情绪共鸣',
    analysis: '前半句（发疯了）和后半句（一切都好）完全矛盾，制造荒诞感。这种自我解嘲式的「假没事」是现代人情绪管理的集体白描，转发即代言。',
    lang: 'zh',
  },
  {
    id: 'zibochizi',
    text: '淄博烧烤：真诚是最好的套路。',
    source: '淄博文旅营销现象，2023年',
    category: '情绪共鸣',
    analysis: '「真诚是最好的套路」在后营销时代是最强的元认知。不是因为真诚，而是因为说出「我们真诚」——这句话本身就是套路，但它能用，因为它说中了用户渴望被真诚对待的心。',
    lang: 'zh',
  },

  // ── 反差对比 · 中文 ──
  {
    id: 'yaolingyao',
    text: '遥遥领先。',
    source: '华为余承东口头禅，2023年后被全面梗化',
    category: '反差对比',
    analysis: '原是真诚的产品自夸，因为用得过于频繁而变成全网梗。梗化之后反而传播力更强——所有人都在用它形容「某件事明显好过另一件事」，品牌记忆反而被强化。',
    lang: 'zh',
  },
  {
    id: 'chunpure',
    text: '纯纯的废物。（含义：我今天什么都没做，感觉还挺好的）',
    source: '「纯纯的XX」前缀句式，2023-2024年流行',
    category: '反差对比',
    analysis: '「纯纯的」是强化副词，「废物」是自嘲名词，两者结合反而产生一种反骄傲。彻底放弃的人比半努力的人更有互联网存在感——这是反内卷文化的文案体现。',
    lang: 'zh',
  },
  {
    id: 'bumaiguixing',
    text: '不是xx买不起，而是xx更有性价比。',
    source: '小红书消费反转句式，2023-2024年顶流',
    category: '反差对比',
    analysis: '把「买不起」的窘迫转化为「我更聪明」的优越感。这个句式的成功在于：用一句话完成了情绪翻转，读者从可怜自己变成欣赏自己，转发即炫耀。',
    lang: 'zh',
  },
  {
    id: 'duoba-perday',
    text: '今天的多巴胺是一杯冰美式。',
    source: '多巴胺穿搭/生活方式文案，2023年起',
    category: '反差对比',
    analysis: '用神经科学词汇美化日常小事——「多巴胺」把「我喝了一杯咖啡」升格成了「我在主动管理情绪化学物质」。消费行为被赋予了自我照顾的正当性。',
    lang: 'zh',
  },

  // ── 极简有力 · 中文 ──
  {
    id: 'nadiyige',
    text: '那就这样吧。',
    source: '哀叹句式，2024年网络高频表达',
    category: '极简有力',
    analysis: '五个字，什么都没说，什么都说完了。放弃解释、放弃争论、放弃期待——这是互联网时代情绪最完整的句子之一。越简短的接受越有力量。',
    lang: 'zh',
  },
  {
    id: 'bulijie',
    text: '我不理解。（但完全理解）',
    source: '反讽用法，2024年流行',
    category: '极简有力',
    analysis: '用「不理解」表达完全理解，反向操作制造幽默。它说的是：这件事荒诞到让我假装不懂才能消化。距离感即幽默感，网感的核心之一。',
    lang: 'zh',
  },
  {
    id: 'xianyanbaoming',
    text: '显眼包报到。',
    source: '「显眼包」，2023-2024年顶流词汇',
    category: '极简有力',
    analysis: '「显眼包」原是贬义（太出风头），但被年轻人反向接管为自我标签。主动承认「我就是要抢眼」，把可能被嘲弄的特质变成身份宣言。',
    lang: 'zh',
  },
  {
    id: 'mingtian-jian',
    text: '明天见。',
    source: 'Manner Coffee 咖啡杯印语',
    category: '极简有力',
    analysis: '三个字完成了所有品牌想说的：我们会在，你会回来，这是关系不是交易。比任何「欢迎再次光临」都有温度，因为它假设了一个未来。',
    lang: 'zh',
  },

  // ── 身份认同 · 中文 ──
  {
    id: 'daoitforplot',
    text: '为了故事感，冲了。',
    source: '「Do it for the plot」中文化，2024年流行',
    category: '身份认同',
    analysis: '把鲁莽的决定升格为人生叙事的需要——我不是冲动，我是在给自己的人生剧本添加情节。把行动的理由从「对不对」变成「好不好看」，彻底解放决策焦虑。',
    lang: 'zh',
  },
  {
    id: 'jiuchushi',
    text: '就出去时，我是普通人；回来时，我还是普通人，但我去过了。',
    source: '文旅/旅行类种草反套路文案',
    category: '身份认同',
    analysis: '不承诺「旅行改变你」，只说「你去过了」。这是反鸡汤的诚实表达，在满屏「旅行治愈我」的内容里因为不煽情而反而更有说服力。',
    lang: 'zh',
  },

  // ── 悬念钩子 · 英文 ──
  {
    id: 'girl-math',
    text: 'Girl math: if I return something, that\'s free money. Which means I can buy something else.',
    source: 'TikTok trend, 2023, millions of videos',
    category: '悬念钩子',
    analysis: 'The joke IS the logic — deliberately flawed reasoning presented as ironclad. It works because everyone has done this exact mental math. The format turned self-aware irrationality into a community ritual that brands immediately started co-opting.',
    lang: 'en',
  },
  {
    id: 'very-demure',
    text: 'Very demure. Very mindful.',
    source: 'Jools Lebron, TikTok, July 2024 — peak virality within days',
    category: '极简有力',
    analysis: 'A workplace presentation tip that became a universal aesthetic descriptor. "Demure" was barely used before this. The repetitive "very" structure made it instantly quotable and parodiable — the meme mechanism was built into the phrasing itself.',
    lang: 'en',
  },
  {
    id: 'brat-era',
    text: 'brat summer.',
    source: 'Charli XCX, June 2024 — fastest brand co-option of any trend',
    category: '身份认同',
    analysis: 'Two words, no capitals, no explanation. The deliberate underdesign (lime green, sloppy font) WAS the aesthetic. Every brand scrambled to be "brat" within a week — which proved the point: brat is too fast and sloppy to be owned by a brand.',
    lang: 'en',
  },
  {
    id: 'do-it-plot',
    text: 'Do it for the plot.',
    source: 'Gen Z phrase, mainstream 2023-2025',
    category: '身份认同',
    analysis: 'Reframes impulsive decisions as narrative necessity — you\'re not reckless, you\'re interesting. Shifts the question from "is this smart?" to "will this make a good story?" Completely dissolves decision anxiety by changing the evaluation criteria.',
    lang: 'en',
  },
  {
    id: 'delulu-solulu',
    text: 'Delulu is the solulu.',
    source: 'TikTok, 2023 — intentional misspelling as style',
    category: '反差对比',
    analysis: 'Rhyme + deliberate misspelling = instantly memeable. The serious argument (manifesting works) wrapped in unserious packaging (baby talk) lets people believe it without being embarrassed about believing it. The irony gives plausible deniability.',
    lang: 'en',
  },
  {
    id: 'roman-empire',
    text: 'My Roman Empire: [thing you think about constantly but never mention].',
    source: 'TikTok trend, late 2023',
    category: '情绪共鸣',
    analysis: 'Gave people a format to confess their most specific, unexplained obsessions. The Roman Empire framing made small fixations feel historically significant. The trend worked because the specificity of each answer was more interesting than the format itself.',
    lang: 'en',
  },
  {
    id: 'normalize',
    text: 'Normalize [thing brands want you to do but frame as social progress].',
    source: 'Wellness/brand copy hijacking of activist language, 2022-2025',
    category: '反差对比',
    analysis: '"Normalize" was originally used for destigmatization. Brands captured it to make ordinary consumption sound like social justice. The backlash ("normalize not normalizing everything") came fast — which is what healthy internet reflexes look like.',
    lang: 'en',
  },
  {
    id: 'brain-rot',
    text: 'This is peak brain rot and I\'m okay with it.',
    source: 'Self-description for absurdist content, 2024 Oxford Word of the Year',
    category: '情绪共鸣',
    analysis: '"Brain rot" was Oxford\'s 2024 word of the year — the fact that people nominated a self-diagnosis of their own media consumption says something. Owning your mindless content habits became more authentic than pretending to have taste.',
    lang: 'en',
  },
  {
    id: 'in-my-era',
    text: 'In my villain era. / In my healing era. / In my unbothered era.',
    source: 'Era framing, Taylor Swift fandom origin, mainstream 2023-2025',
    category: '身份认同',
    analysis: 'Borrowed from album-cycle thinking: your life has eras, not states. "Era" implies it\'s deliberate, temporary, and aesthetically coherent. Brands immediately used it ("in our sustainability era") which is how you know a meme has peaked.',
    lang: 'en',
  },
];
