/**
 * 内置迷因(开箱即玩)。都挑传播史相对清楚、可查证的经典迷因。
 * 用户可通过「复制采集指令」让任意 AI 产出更多,导入即玩。
 */

import type { Meme } from './types';

const doge: Meme = {
  id: 'doge',
  title: 'Doge(柴犬)',
  summary: '一只侧眼柴犬 + 彩色 Comic Sans 蹩脚英文内心独白,后来还变成了加密货币。',
  startId: 'now',
  originId: 'photo',
  stations: [
    {
      id: 'now',
      kind: 'mutation',
      art: 'doge',
      title: '你熟悉的那只 Doge',
      date: '2013',
      platform: '全网',
      body: '一张柴犬侧眼看镜头的照片,四周飘着彩色 Comic Sans 字体的蹩脚英文内心独白:「such wow、much X、very Y、so Z」。它是怎么从一张普通狗照片变成这样的?先看看[[reddit|它爆红的那一刻]],或者顺流看看它[[coin|后来怎么变成了钱]]。',
      links: [
        { to: 'reddit', rel: 'back', label: '它是怎么爆红的' },
        { to: 'spelling', rel: 'variant', label: '"doge" 这拼写哪来的' },
        { to: 'coin', rel: 'forward', label: '后来变成了一种货币' },
      ],
    },
    {
      id: 'reddit',
      kind: 'spread',
      art: 'doge',
      title: '2013:蹩脚英文「doge speak」引爆',
      date: '2013 年中',
      platform: 'Reddit / Tumblr',
      body: '2013 年夏秋,这张柴犬照片配上刻意错乱的语法(把 very/much/so 乱接名词)在 Reddit、Tumblr 上迅速扩散,形成了独特的「doge speak」。这种人人都能照着造句的模板,是它裂变的关键。再往前一步,[[photo|照片里的狗本尊是谁]]?',
      links: [
        { to: 'photo', rel: 'back', label: '照片本尊是谁' },
        { to: 'now', rel: 'forward', label: '回到如今的形态' },
      ],
      sources: [{ label: 'Know Your Meme: Doge' }],
    },
    {
      id: 'photo',
      kind: 'origin',
      art: 'doge',
      title: '起点:2010 年,柴犬 Kabosu',
      date: '2010.02',
      platform: '个人博客(日本)',
      body: '源头是一只被收养的日本柴犬 Kabosu。主人佐藤敦子(一位幼儿园老师)2010 年在博客上传了它坐在沙发上、微微侧眼的照片——正是这张表情,日后成了全世界的 Doge。它如何[[reddit|被玩成一个梗]]?',
      links: [{ to: 'reddit', rel: 'forward', label: '它如何被玩成梗' }],
      sources: [{ label: 'Kabosu / 佐藤敦子 博客' }],
    },
    {
      id: 'spelling',
      kind: 'spread',
      art: 'doge',
      title: '「doge」这个拼写的来历',
      date: '2005 / 2010',
      platform: 'Homestar Runner',
      body: '把 dog 故意拼成「doge」并非 2013 年才有:早在 2005 年动画《Homestar Runner》里就出现过这个玩笑拼写。它像一个沉睡的语言彩蛋,等到 2013 年柴犬照片出现,两者一拍即合。回到[[now|如今的 Doge]]。',
      links: [{ to: 'now', rel: 'forward', label: '回到如今的 Doge' }],
    },
    {
      id: 'coin',
      kind: 'mutation',
      art: 'coin',
      title: '2013.12:Doge 变成了 Dogecoin',
      date: '2013.12',
      platform: '加密货币',
      body: '2013 年底,程序员 Billy Markus 与 Jackson Palmer 半开玩笑地用 Doge 形象做了一种加密货币 Dogecoin,本意是讽刺币圈的狂热。没想到梗的亲和力反过来给了它生命力。它后来还被[[musk|名人反复助推]]。',
      links: [
        { to: 'musk', rel: 'forward', label: '名人助推与复活' },
        { to: 'now', rel: 'back', label: '回到梗本身' },
      ],
    },
    {
      id: 'musk',
      kind: 'decline',
      art: 'coin',
      title: '名人助推:一次次被拉回聚光灯',
      date: '2019 起',
      platform: 'Twitter/X',
      body: '此后每隔一段时间,名人(尤其是马斯克)的一条推文就能把 Dogecoin 和 Doge 形象重新顶上热搜——这是典型的「大 V 助推」让一个老梗反复复活。Kabosu 本尊于 2024 年离世,人们又一次集体缅怀。',
      links: [{ to: 'coin', rel: 'back', label: '回到 Dogecoin 的诞生' }],
    },
  ],
  factors: ['remix', 'incongruity', 'lowbar', 'ingroup', 'platform'],
  analysis:
    'Doge 的走红是几股力量叠加:蹩脚英文「doge speak」是一个极易套用的模板(可改编性 + 参与门槛低),谁都能照着给自家宠物配字;柴犬那张一本正经的侧眼与荒诞内心独白之间的反差制造了记忆点(反差意外);会心一笑背后是一层网络亚文化的暗号(圈层信号);而它以图片形态在 Reddit/Tumblr 这类视觉平台传播,天然契合平台机制(平台适配)。后期 Dogecoin 与名人助推则让它一次次复活。',
};

const rickroll: Meme = {
  id: 'rickroll',
  title: 'Rickroll(瑞克摇)',
  summary: '一个看似正经的链接,点开却是 Rick Astley 1987 年的《Never Gonna Give You Up》。',
  startId: 'now',
  originId: 'duckroll',
  stations: [
    {
      id: 'now',
      kind: 'mutation',
      art: 'play',
      title: '你又被 Rickroll 了',
      date: '至今',
      platform: '全网',
      body: '有人发你一个「重要资料」的链接,满心期待点开——结果是 Rick Astley 在 1987 年 MV 里边跳边唱《Never Gonna Give You Up》。这个「诱骗式跳转」的套路是哪来的?它其实有个更早的[[duckroll|鸭子祖宗]]。',
      links: [
        { to: 'fourchan', rel: 'back', label: '第一次 Rickroll' },
        { to: 'song', rel: 'variant', label: '那首歌本身的故事' },
        { to: 'peak', rel: 'forward', label: '它怎么破圈的' },
      ],
    },
    {
      id: 'fourchan',
      kind: 'spread',
      art: 'play',
      title: '2007:第一次「Rickroll」',
      date: '2007.05',
      platform: '4chan',
      body: '2007 年,有人在 4chan 上把一个备受期待的《侠盗猎车手 IV》预告链接,偷换成了 Rick Astley 的 MV。「rickroll」这个词就此诞生。它沿用的正是更早的[[duckroll|duckroll]]套路——只是把payload换成了这首歌。',
      links: [
        { to: 'duckroll', rel: 'back', label: '套路的祖宗:duckroll' },
        { to: 'now', rel: 'forward', label: '回到如今' },
      ],
      sources: [{ label: 'Know Your Meme: Rickroll' }],
    },
    {
      id: 'duckroll',
      kind: 'origin',
      art: 'duck',
      title: '起点:duckroll(鸭子诱骗)',
      date: '2006',
      platform: '4chan',
      body: '一切的源头是 4chan 上的「duckroll」:论坛把某个词自动替换成一张「装着轮子的鸭子」图,于是点开看似正经的链接总会跳到那只鸭子。这种「诱骗式跳转」的恶作剧格式,就是 Rickroll 的直接祖先。换个 payload,它就[[fourchan|变成了 Rickroll]]。',
      links: [{ to: 'fourchan', rel: 'forward', label: '换成那首歌之后' }],
    },
    {
      id: 'song',
      kind: 'spread',
      art: 'play',
      title: 'payload 本身:1987 的那首歌',
      date: '1987',
      platform: '流行音乐',
      body: '被拿来当「陷阱」的,是英国歌手 Rick Astley 1987 年的单曲《Never Gonna Give You Up》——一首旋律洗脑、MV 舞步略显尴尬的经典。正是这份「无害又上头」的气质,让它成了完美的恶作剧素材。看它如何[[peak|从恶作剧变成全民梗]]。',
      links: [{ to: 'peak', rel: 'forward', label: '破圈时刻' }],
    },
    {
      id: 'peak',
      kind: 'peak',
      art: 'play',
      title: '2008:破圈进入主流',
      date: '2008',
      platform: '主流媒体',
      body: '2008 年愚人节,YouTube 把首页所有精选视频都做成了 Rickroll;同年 Rick Astley 本人还在梅西感恩节大游行上突然现身开唱。恶作剧就此从论坛暗号变成全民都懂的梗。此后它成了[[evergreen|常青的互联网仪式]]。',
      links: [
        { to: 'evergreen', rel: 'forward', label: '常青与复活' },
        { to: 'now', rel: 'back', label: '回到套路本身' },
      ],
    },
    {
      id: 'evergreen',
      kind: 'decline',
      art: 'play',
      title: '常青:十几年后依然有效',
      date: '2020s',
      platform: 'YouTube',
      body: '十几年过去,原版 MV 在 YouTube 收获超过 10 亿次播放,Rickroll 仍是屡试不爽的整蛊,甚至被用在抗议、发布会彩蛋里。一个「无害的惊吓」为什么能长盛不衰?去[[now|再被摆一道]]或想想它的成因。',
      links: [{ to: 'now', rel: 'back', label: '再被摆一道' }],
    },
  ],
  factors: ['incongruity', 'lowbar', 'ingroup', 'amplifier', 'platform'],
  analysis:
    'Rickroll 的持久魅力在于:它建立在「诱骗式跳转」这个可无限复用的格式上(可改编性),而参与成本极低——你只要粘贴一个链接(参与门槛低);点开瞬间的「被摆一道」制造了无害的意外与反差(反差意外);懂的人相视一笑,是一种圈内默契(圈层信号);2008 年 YouTube 与主流媒体的助推让它彻底破圈(大V助推);而它本质是一个超链接恶作剧,与论坛/网页的分享机制完美契合(平台适配)。',
};

const thisIsFine: Meme = {
  id: 'thisisfine',
  title: 'This is fine(没事,挺好的)',
  summary: '一只戴帽子的狗坐在燃烧的房间里,端着咖啡说「This is fine」。',
  startId: 'now',
  originId: 'comic',
  stations: [
    {
      id: 'now',
      kind: 'mutation',
      art: 'fire',
      title: '烈火中的「This is fine」',
      date: '2016 起',
      platform: '全网',
      body: '一只卡通狗坐在着火的房间里,四周烈焰,它却端着咖啡淡定地说:「This is fine.」它被用来形容任何「明明一团糟却假装镇定」的处境。但很多人不知道:它原本[[comic|是一整则更长的漫画]]。',
      links: [
        { to: 'crop', rel: 'back', label: '它被裁成两格之前' },
        { to: 'politics', rel: 'forward', label: '它如何进入政治场' },
      ],
    },
    {
      id: 'crop',
      kind: 'spread',
      art: 'fire',
      title: '2014:被裁成两格',
      date: '2014',
      platform: 'Tumblr / Twitter',
      body: '原漫画有六格,结局其实相当黑暗。2014 年前后,网友只截取了前两格——狗说「This is fine」的那一刻——脱离原语境后,它变成了万能的「嘴硬式镇定」表情。它的[[comic|完整版]]是什么样?',
      links: [
        { to: 'comic', rel: 'back', label: '看完整六格' },
        { to: 'now', rel: 'forward', label: '回到如今' },
      ],
    },
    {
      id: 'comic',
      kind: 'origin',
      art: 'fire',
      title: '起点:2013,KC Green 的《On Fire》',
      date: '2013.01',
      platform: '网络漫画 Gunshow',
      body: '源头是漫画家 KC Green 2013 年的网络漫画《Gunshow》第 648 话《On Fire》。完整六格里,那只狗最终在烈火中融化——是一则关于「否认与自我毁灭」的黑色幽默。被截掉后半段后,它才变得「正能量」。看它[[crop|被裁剪]]后发生了什么。',
      links: [{ to: 'crop', rel: 'forward', label: '被裁剪之后' }],
      sources: [{ label: 'KC Green, Gunshow #648 "On Fire"' }],
    },
    {
      id: 'politics',
      kind: 'peak',
      art: 'fire',
      title: '2016:成为「灾难现场」的代名词',
      date: '2016',
      platform: '推特 / 新闻',
      body: '2016 年前后,它被大量用于形容政治与社会的「灾难现场」,一度被政党官方账号引用又删除,彻底破圈。凡是「局面失控但还在强撑」,人们就甩出这只狗。它后来还[[notfine|反过来被原作者玩了一把]]。',
      links: [
        { to: 'notfine', rel: 'forward', label: '"This is not fine"' },
        { to: 'now', rel: 'back', label: '回到那两格' },
      ],
    },
    {
      id: 'notfine',
      kind: 'decline',
      art: 'fire',
      title: '复活:「This is NOT fine」',
      date: '2016 起 / 2020',
      platform: '周边 / 公益',
      body: '原作者 KC Green 顺势推出续作与周边「This is NOT fine」——那只狗终于跳起来救火,把「假装没事」翻转成「行动起来」。2020 年疫情期间,这个梗又一次被集体唤醒。',
      links: [{ to: 'politics', rel: 'back', label: '回到破圈时刻' }],
    },
  ],
  factors: ['emotion', 'remix', 'timing', 'ingroup', 'platform'],
  analysis:
    'This is fine 击中的是一种普遍情绪:在失控局面里假装镇定的无力与自嘲(情绪强度)。它是一个可以套进任何糟糕处境的万能模板(可改编性),尤其在 2016 年的政治与社会动荡里踩中了集体情绪(时机搭车);用它的人彼此心照不宣地共享一种黑色幽默(圈层信号);而两格漫画的形态极适合在推特等平台一图传播(平台适配)。有趣的是,它的走红恰恰来自「断章取义」——截掉了原作更黑暗的结局。',
};

const nyancat: Meme = {
  id: 'nyancat',
  title: 'Nyan Cat(彩虹猫)',
  summary: '身体是 Pop-Tart 饼干的像素猫,拖着彩虹在太空循环飞行,配着魔性的「nyanyan」歌声——其实是一张画和一首歌拼起来的。',
  startId: 'now',
  originId: 'drawing',
  stations: [
    {
      id: 'now',
      kind: 'mutation',
      art: 'nyan',
      title: '你熟悉的那只彩虹猫',
      date: '2011 起',
      platform: '全网',
      body: '一只像素猫,身体是一块草莓味 Pop-Tart 饼干,拖着彩虹在太空里循环飞行,配着魔性的「nyanyanya」歌声。很多人不知道:它其实是两样东西拼起来的——一张[[drawing|像素画]]和一首[[song|日本洗脑曲]]。它后来还[[nft|拍出了天价]]。',
      links: [
        { to: 'combined', rel: 'back', label: '它是怎么拼成、爆红的' },
        { to: 'song', rel: 'variant', label: '那首魔性的歌哪来的' },
        { to: 'nft', rel: 'forward', label: '后来拍出天价' },
      ],
    },
    {
      id: 'drawing',
      kind: 'origin',
      art: 'nyan',
      title: '起点之一:2011,Pop Tart Cat',
      date: '2011.04',
      platform: 'LOL-Comics(个人站)',
      body: '2011 年 4 月,美国插画师 Christopher Torres(网名 prguitarman)在自己的站点发布了一张像素猫 GIF——猫的身体是一块 Pop-Tart 饼干,他叫它「Pop Tart Cat」。这就是彩虹猫的[[combined|视觉源头]]。',
      links: [{ to: 'combined', rel: 'forward', label: '它如何被配上歌' }],
      sources: [{ label: 'Wikipedia: Nyan Cat', url: 'https://en.wikipedia.org/wiki/Nyan_Cat' }],
    },
    {
      id: 'song',
      kind: 'spread',
      art: 'nyan',
      title: '起点之二:2010,日本的「nyanyan」曲',
      date: '2010',
      platform: 'Nico Nico / Vocaloid 圈',
      body: '另一半来自日本:2010 年 Vocaloid 圈作者 daniwellP 做了一首洗脑短曲《Nyanyanyanya!》,由 UTAU 角色桃音モモ演唱。这段「nyanyan」旋律,后来成了彩虹猫的[[combined|听觉源头]]。',
      links: [{ to: 'combined', rel: 'forward', label: '它如何被配上画' }],
      sources: [
        { label: 'Know Your Meme: Nyan Cat', url: 'https://knowyourmeme.com/memes/nyan-cat-pop-tart-cat' },
      ],
    },
    {
      id: 'combined',
      kind: 'spread',
      art: 'nyan',
      title: '2011.04:图 + 歌拼在一起,叫「Nyan Cat」',
      date: '2011.04',
      platform: 'YouTube',
      body: '2011 年 4 月,YouTube 用户 saraj00n 把 prguitarman 的[[drawing|像素猫]]和 daniwellP 的[[song|那首歌]]拼成一段循环视频,取名「Nyan Cat」。图与歌一拍即合,迅速病毒式扩散,把两件原本各自的作品变成了同一个梗。',
      links: [
        { to: 'drawing', rel: 'back', label: '画本身的来历' },
        { to: 'song', rel: 'back', label: '歌本身的来历' },
        { to: 'peak', rel: 'forward', label: '它怎么爆的' },
      ],
    },
    {
      id: 'peak',
      kind: 'peak',
      art: 'nyan',
      title: '2011:年度病毒视频',
      date: '2011',
      platform: 'YouTube / 全网',
      body: '2011 年,Nyan Cat 成为当年最火的病毒视频之一,YouTube 播放以千万计,催生了无数语言版本、时长恶搞(10 小时版)、翻唱与网页小游戏。这个梗[[nft|十年后又火了一次]]。',
      links: [
        { to: 'nft', rel: 'forward', label: '十年后的复活' },
        { to: 'combined', rel: 'back', label: '回到它拼成的那一刻' },
      ],
    },
    {
      id: 'nft',
      kind: 'decline',
      art: 'nyan',
      title: '2021:原图拍成 NFT',
      date: '2021.02',
      platform: 'NFT 市场',
      body: '2021 年 2 月,原作者 Chris Torres 把最初的 Nyan Cat GIF 作为 NFT 拍卖,成交价约 300 ETH(当时约 59 万美元),成为 NFT 数字艺术热潮的标志性事件之一,让这个十年老梗重回聚光灯。',
      links: [{ to: 'peak', rel: 'back', label: '回到它最火的时候' }],
      sources: [{ label: 'Wikipedia: Nyan Cat', url: 'https://en.wikipedia.org/wiki/Nyan_Cat' }],
    },
  ],
  factors: ['remix', 'incongruity', 'emotion', 'platform'],
  analysis:
    'Nyan Cat 的走红是一次完美的拼接:荒诞可爱的像素猫配上洗脑循环曲,无厘头的组合本身就抓人(反差意外),萌感与欢乐情绪一击即中(情绪强度);循环视频 / GIF 的形态天生适合在 YouTube 和网页里疯传(平台适配);而极简形象又给了网友无穷的二创空间——各种语言版、超长版、翻唱、小游戏层出不穷(可改编性)。十年后的 NFT 拍卖又给这个老梗续了一把火。',
};

const pepe: Meme = {
  id: 'pepe',
  title: 'Pepe the Frog(佩佩蛙)',
  summary: '一只能表达任何情绪的绿青蛙,从「feels good man」的漫画,一路走到被挪用、被作者「杀死」、又被重新挪用。',
  startId: 'now',
  originId: 'comic',
  stations: [
    {
      id: 'now',
      kind: 'mutation',
      art: 'pepe',
      title: '万物皆可 Pepe',
      date: '2015 起',
      platform: '全网',
      body: '一只绿色卡通青蛙,被画成各种表情——爽(feels good)、丧(feels bad)、得意、愤怒——成了万能的情绪反应图。但它的经历远比一张表情包复杂:它有一个[[comic|温和的漫画起点]],也卷进过[[controversy|一场巨大的争议]]。',
      links: [
        { to: 'feelsgood', rel: 'back', label: '它怎么传开的' },
        { to: 'rare', rel: 'variant', label: '"rare Pepe" 是什么' },
        { to: 'controversy', rel: 'forward', label: '它怎么卷入争议' },
      ],
    },
    {
      id: 'comic',
      kind: 'origin',
      art: 'pepe',
      title: '起点:2005,《Boy’s Club》',
      date: '2005',
      platform: '漫画 / Myspace',
      body: '源头是漫画家 Matt Furie 2005 年的漫画《Boy’s Club》。有一格里 Pepe 把裤子整个褪到脚踝上厕所,被问为什么,它答「feels good man」。正是这句[[feelsgood|「feels good man」]]日后被截成了反应图。',
      links: [{ to: 'feelsgood', rel: 'forward', label: '它如何变成反应图' }],
      sources: [{ label: 'Wikipedia: Pepe the Frog', url: 'https://en.wikipedia.org/wiki/Pepe_the_Frog' }],
    },
    {
      id: 'feelsgood',
      kind: 'spread',
      art: 'pepe',
      title: '「Feels Good Man」与它的表情家族',
      date: '2008 起',
      platform: '4chan / MySpace',
      body: '2000 年代末,「feels good man」这格被单独截出,在 4chan 等论坛当反应图疯传;很快又衍生出丧脸「feels bad man」、得意脸、愤怒脸等一整个表情家族。可无限重画的特性,是它裂变的关键。它甚至催生了[[rare|"稀有 Pepe" 的收藏文化]]。',
      links: [
        { to: 'comic', rel: 'back', label: '这只青蛙哪来的' },
        { to: 'rare', rel: 'forward', label: '"稀有 Pepe"' },
      ],
    },
    {
      id: 'rare',
      kind: 'mutation',
      art: 'pepe',
      title: '2015:「稀有 Pepe」收藏热',
      date: '2015–2016',
      platform: '4chan / 区块链',
      body: '网友开始把自制的 Pepe 变体当「收藏品」交换,戏称「rare Pepe(稀有佩佩)」,还半认真地在 eBay 挂牌。2016 年更出现了基于区块链的「Rare Pepe」卡牌,是最早的数字藏品实验之一。这份可无限二创的属性,也为它日后[[controversy|被各方挪用]]埋下伏笔。',
      links: [
        { to: 'feelsgood', rel: 'back', label: '回到表情家族' },
        { to: 'controversy', rel: 'forward', label: '被卷入争议' },
      ],
    },
    {
      id: 'controversy',
      kind: 'decline',
      art: 'pepe',
      title: '2016:被挪用,被列为仇恨符号',
      date: '2016',
      platform: '美国大选 / 网络',
      body: '2016 年美国大选期间,Pepe 被部分极端网络群体挪用、与仇恨内容绑定。当年 9 月,反诽谤联盟(ADL)把它列入仇恨符号数据库——但同时明确指出,绝大多数 Pepe 的使用与仇恨无关。原作者对此深感痛心,于是有了[[killed|他亲手「杀死」Pepe]]。',
      links: [
        { to: 'rare', rel: 'back', label: '回到 rare Pepe' },
        { to: 'killed', rel: 'forward', label: '作者的回应' },
      ],
      sources: [{ label: 'ADL: Pepe the Frog', url: 'https://www.adl.org/resources/hate-symbol/pepe-frog' }],
    },
    {
      id: 'killed',
      kind: 'mutation',
      art: 'pepe',
      title: '2017:作者亲手「杀死」Pepe',
      date: '2017',
      platform: '漫画 / 法律',
      body: 'Matt Furie 2017 年画了一格让 Pepe「下葬」,象征性地终结它;并对多起仇恨或未授权的商业使用发起法律行动,试图夺回自己的角色。故事本可到此为止,但两年后它又[[reclaim|以另一种面貌复活]]。',
      links: [
        { to: 'controversy', rel: 'back', label: '回到争议' },
        { to: 'reclaim', rel: 'forward', label: '它的复活' },
      ],
    },
    {
      id: 'reclaim',
      kind: 'decline',
      art: 'pepe',
      title: '2019:在香港等语境被重新挪用',
      date: '2019 / 2020',
      platform: '街头 / 纪录片',
      body: '2019 年,Pepe 在香港的抗议语境里被大量用作一个不带西方包袱的普通卡通形象,成了一次「再挪用」。2020 年纪录片《Feels Good Man》完整梳理了它从无害漫画到被争夺、再被重新赋义的全过程——一个空白模板可以被填进任何意义。',
      links: [{ to: 'killed', rel: 'back', label: '回到作者的告别' }],
      sources: [{ label: '纪录片《Feels Good Man》(2020)' }],
    },
  ],
  factors: ['remix', 'emotion', 'ingroup', 'platform'],
  analysis:
    'Pepe 之所以成为迷因,核心是它几乎是一张「空白情绪模板」:同一张青蛙脸可以被重画成任何心情(可改编性),每一种表情都直击一种情绪(情绪强度);它长在 4chan 等图版的反应图文化里,是圈内人彼此确认的暗号(圈层信号),而反应图形态又与论坛/图版机制天然契合(平台适配)。也正因为它是一块可任意填意义的空白模板,才会在 2016 年被挪用、被列为仇恨符号,又能在 2019 年被重新赋予完全不同的含义——这既是它的生命力,也是它的争议根源。',
};

const grumpycat: Meme = {
  id: 'grumpycat',
  title: 'Grumpy Cat(暴躁猫)',
  summary: '一只天生「臭脸」的猫 Tardar Sauce,一张 Reddit 照片让它成了全网的坏心情代言人。',
  startId: 'now',
  originId: 'reddit',
  stations: [
    {
      id: 'now',
      kind: 'mutation',
      art: 'grumpy',
      title: '全网的坏心情代言人',
      date: '2012 起',
      platform: '全网',
      body: '一张永远撇着嘴、一脸嫌弃的猫脸,配上「NO」「我开心过一次,糟透了」之类的毒舌配字,成了表达坏心情的万能表情包。这张脸其实来自一只真实的猫——它[[reddit|第一次出现]]时,大家还以为是 P 的。',
      links: [
        { to: 'real', rel: 'back', label: '它是真猫吗' },
        { to: 'peak', rel: 'forward', label: '它怎么火成现象的' },
      ],
    },
    {
      id: 'reddit',
      kind: 'origin',
      art: 'grumpy',
      title: '起点:2012.09,一张 Reddit 照片',
      date: '2012.09',
      platform: 'Reddit',
      body: '2012 年 9 月,Bryan Bundesen 把姐姐 Tabatha 养的猫「Tardar Sauce」的照片发到 Reddit。它天生的臭脸表情瞬间引爆热度。可当时很多人[[real|不相信这是真的]]。',
      links: [{ to: 'real', rel: 'forward', label: '大家以为是P图' }],
      sources: [{ label: 'Wikipedia: Grumpy Cat', url: 'https://en.wikipedia.org/wiki/Grumpy_Cat' }],
    },
    {
      id: 'real',
      kind: 'spread',
      art: 'grumpy',
      title: '「这猫是真的」+ 表情包量产',
      date: '2012.09',
      platform: 'Reddit / 全网',
      body: '网友怀疑照片是 P 的,主人于是发了更多照片、视频自证——那张臭脸是猫的侏儒症与地包天造成的,真实存在。真相反而助推了热度,毒舌配字的表情包开始量产。它很快[[peak|火成了现象级]]。',
      links: [
        { to: 'reddit', rel: 'back', label: '第一张照片' },
        { to: 'peak', rel: 'forward', label: '现象级爆红' },
      ],
    },
    {
      id: 'peak',
      kind: 'peak',
      art: 'grumpy',
      title: '2013:年度迷因',
      date: '2013',
      platform: '全网 / 线下',
      body: '2013 年,Grumpy Cat 成为现象级迷因:拿下当年 Webby 奖「年度迷因」,亮相 SXSW,登上各种媒体。它不再只是表情包,而是一个真正的[[empire|商业 IP]]。',
      links: [
        { to: 'empire', rel: 'forward', label: '它的商业帝国' },
        { to: 'real', rel: 'back', label: '回到它爆红之初' },
      ],
    },
    {
      id: 'empire',
      kind: 'mutation',
      art: 'grumpy',
      title: '从表情包到商业 IP',
      date: '2013–2018',
      platform: '出版 / 影视 / 商业',
      body: '主人成立 Grumpy Cat 有限公司,出书、卖周边,2014 年还拍了一部电视电影《Grumpy Cat’s Worst Christmas Ever》;2018 年公司还打赢了一场商标侵权官司获赔数十万美元。一张臭脸变成了一门生意。',
      links: [
        { to: 'peak', rel: 'back', label: '回到现象级时刻' },
        { to: 'death', rel: 'forward', label: '故事的结尾' },
      ],
    },
    {
      id: 'death',
      kind: 'decline',
      art: 'grumpy',
      title: '2019:Tardar Sauce 离世',
      date: '2019.05',
      platform: '全网悼念',
      body: '2019 年 5 月,Tardar Sauce 因病离世,享年七岁。全网集体悼念这只「不开心」却给无数人带来快乐的猫。它的臭脸表情,至今仍是坏心情的通用语言。',
      links: [{ to: 'empire', rel: 'back', label: '回到它的巅峰' }],
    },
  ],
  factors: ['emotion', 'remix', 'incongruity', 'platform'],
  analysis:
    'Grumpy Cat 的走红,首先赢在一张脸就是一种情绪:那副天生的臭脸精准对应了人人都有的坏心情与厌世感(情绪强度),可爱的猫却永远一脸嫌弃,这种反差本身就抓人(反差意外)。它是标准的图片表情包(image macro),谁都能套上一句毒舌配字(可改编性);而它诞生并疯传于 Reddit 的表情包文化,形态与平台机制完美契合(平台适配)。真实存在、又被精心运营成 IP,让它从一张图长成了持续多年的现象。',
};

const duang: Meme = {
  id: 'duang',
  title: 'duang(成龙 · 霸王广告)',
  summary: '一个没有确切意思却极其传神的拟声词,来自成龙十年前的洗发水广告,被 B 站鬼畜翻红、一夜刷屏微博。',
  startId: 'now',
  originId: 'ad',
  stations: [
    {
      id: 'now',
      kind: 'mutation',
      art: 'play',
      title: '「duang」是什么意思?',
      date: '2015 起',
      platform: '全网',
      body: '「duang」是一个没有确切意思、却极其传神的拟声词——形容某种「唰地一下、特效加满」的效果,网友还生造了一个字:把「成龙」的「成」摞在「龙」上来写它。它其实来自一支[[ad|十年前的洗发水广告]]。',
      links: [
        { to: 'viral', rel: 'back', label: '它怎么突然爆红' },
        { to: 'ad', rel: 'variant', label: '那支老广告' },
      ],
    },
    {
      id: 'ad',
      kind: 'origin',
      art: 'play',
      title: '起点:2004,成龙的霸王洗发水广告',
      date: '2004',
      platform: '电视广告',
      body: '「duang」最早出自成龙 2004 年代言的霸王防脱洗发水广告。他描述头发加了特效后「很黑、很亮、很柔」,并用一声「duang~」来形容那种唰地一下的效果。这个拟声词当时并不起眼,直到[[remix|十年后被网友翻出来]]。',
      links: [
        { to: 'remix', rel: 'forward', label: '十年后被翻红' },
        { to: 'bawang', rel: 'variant', label: '这广告的黑历史' },
      ],
      sources: [{ label: 'Wikipedia: Duang', url: 'https://en.wikipedia.org/wiki/Duang' }],
    },
    {
      id: 'bawang',
      kind: 'spread',
      art: 'play',
      title: '广告的黑历史:霸王风波',
      date: '2010',
      platform: '新闻',
      body: '这支广告后来变得有点尴尬:2010 年有报道质疑霸王洗发水含有争议成分二噁烷,品牌陷入风波、销量下滑(公司当时予以否认)。多年后老广告被翻出来玩梗,也就多了一层反差意味。',
      links: [{ to: 'ad', rel: 'back', label: '回到那支广告' }],
    },
    {
      id: 'remix',
      kind: 'spread',
      art: 'play',
      title: '2015.02:B 站鬼畜把它翻出来',
      date: '2015.02',
      platform: '哔哩哔哩',
      body: '2015 年 2 月,有网友把这支老广告做成鬼畜视频,和庞麦郎的《我的滑板鞋》混剪在一起,把「duang」这个音单独拎出来反复循环。魔性的节奏让它一夜之间被无数人记住,并很快[[viral|冲上微博刷屏]]。',
      links: [
        { to: 'ad', rel: 'back', label: 'duang 最早哪来的' },
        { to: 'viral', rel: 'forward', label: '它如何刷屏' },
      ],
    },
    {
      id: 'viral',
      kind: 'peak',
      art: 'play',
      title: '2015.02:微博刷屏,生造一个字',
      date: '2015.02',
      platform: '微博',
      body: '几天内「duang」在微博被刷了上千万次,网友还生造了一个字——把「成龙」的「成」摞在「龙」上来写它;成龙本人的微博评论区被「duang」淹没,连 BBC、卫报等外媒都来报道这个「无法翻译的中国网络词」。',
      links: [
        { to: 'remix', rel: 'back', label: '谁把它翻出来的' },
        { to: 'decline', rel: 'forward', label: '后来呢' },
      ],
      sources: [{ label: 'BBC / The Guardian 2015 报道' }],
    },
    {
      id: 'decline',
      kind: 'decline',
      art: 'play',
      title: '热潮退去,沉淀成网络词',
      date: '2015 起',
      platform: '全网',
      body: '作为一阵爆发式的流行,「duang」的热度很快回落,但它留在了中文网络的词库里——形容「特效感、突然一下」时,大家仍会甩出一个「duang」。',
      links: [{ to: 'viral', rel: 'back', label: '回到刷屏时刻' }],
    },
  ],
  factors: ['remix', 'platform', 'amplifier', 'incongruity', 'ingroup'],
  analysis:
    '「duang」的爆红是一次典型的鬼畜造梗:一段十年前广告里的无意义拟声词,被 B 站的鬼畜二创重新拼贴、循环放大(可改编性 + 平台适配),魔性到让人过耳不忘。它自带反差——严肃老广告 × 无厘头音效(反差意外);而故事的中心是成龙这样的顶级明星,天然带来话题与媒体放大(大V助推)。它也深植于中文网络的鬼畜/弹幕亚文化,是圈内人心照不宣的暗号(圈层信号)。',
};

export const BUILTIN_MEMES: Meme[] = [doge, rickroll, thisIsFine, nyancat, pepe, grumpycat, duang];
